# Generated by Django 4.2.3 on 2023-07-12 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinks',
            old_name='drinks',
            new_name='drink_name',
        ),
    ]
